[workspace]
resolver = "3"
members = ["crates/kernel-core"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Morgiver/rust-kernel"
authors = ["Morgiver <morgan@morgiver.net>"]

[workspace.lints.rust]
missing_docs = "deny"
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
