[workspace]
resolver = "3"
members = ["crates/kernel-core", "crates/kernel", "crates/kernel-macros", "crates/kernel-testkit", "examples/minimal"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Morgiver/rust-kernel"
authors = ["Morgiver <morgan@morgiver.net>"]

[workspace.dependencies]
kernel-core = { path = "crates/kernel-core", version = "0.1.0" }
kernel = { path = "crates/kernel", version = "0.1.0" }
kernel-macros = { path = "crates/kernel-macros", version = "0.1.0" }
kernel-testkit = { path = "crates/kernel-testkit", version = "0.1.0" }
tokio = { version = "1", default-features = false }

[workspace.lints.rust]
missing_docs = "deny"
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
